name: bump-jslib

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # Set up environment
  bump-jslib:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          echo $GITHUB_REF

      - name: checkout new branch
        if: github.ref == 'refs/head/master'
        run: git checkout -b bump-jslib-${github.actor}

      - name: Bump jslib and commit
        run: |  
          npm run sub:update
          git add jslib
          git commit -m "bump jslib"
          git push -u origin `git branch --show-current`

      - name: Submit PR against master branch
        if: github.ref == 'refs/head/master'
        run: gh pr create --title "Bump jslib" \
                          --body "This is an automated pull request to bump jslib. It was requested by ${github.actor}" \
                          --reviewer eliykat
                          # --reviewer bitwarden/dept-engineering
                          
