name: bump-jslib

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # Set up environment
  setup:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Print job information
        run: |
          echo Detected non-master branch
          echo Creating "jslib bump" commit and pushing to branch: ${GITHUB_REF}

      - name: Configure git
        run: |
          cd $GITHUB_WORKSPACE
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
