name: bump-jslib

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # Create a jslib bump commit on the current branch
  # Used for non-master branches
  create-jslib-commit:
    if: github.ref != 'refs/head/master'
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Print job information
        run: |
          echo Detected non-master branch
          echo Creating "jslib bump" commit and pushing to branch: ${GITHUB_REF}

      # Runs a set of commands using the runners shell
      - name: Bump jslib and commit
        run: |
          npm run sub:update
          git add jslib
          git commit -m "bump jslib"
          git push
