name: Bump jslib

on:
  workflow_dispatch:

jobs:
  bump-jslib:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Setup git config
        run: |
          git config user.name = "GitHub Action Bot"
          git config user.email = "<>"

      - name: Bump jslib and commit
        id: bump
        run: |
          CHECKED_OUT_BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})

          if [ "$CHECKED_OUT_BRANCH_NAME" = "master" ]; then
            TARGET_BRANCH_NAME="auto-bump-jslib"
            git fetch origin
            EXISTING_PR=$(git ls-remote --heads origin $TARGET_BRANCH_NAME | wc -l)
            if [ "$EXISTING_PR" -gt 0 ]; then
              git checkout $TARGET_BRANCH_NAME
              echo "[*] Checked out existing PR branch $TARGET_BRANCH_NAME"
            else
              git checkout -b $TARGET_BRANCH_NAME
              echo "[*] Checked out new branch $TARGET_BRANCH_NAME"
            fi
          else
            TARGET_BRANCH_NAME="$CHECKED_OUT_BRANCH_NAME"
            EXISTING_PR=0
            echo "[*] Running on existing feature branch $TARGET_BRANCH_NAME"
          fi

          echo "::set-output name=target-branch-name::${TARGET_BRANCH_NAME}"
