name: Bump jslib

on:
  workflow_dispatch:

jobs:
  bump-jslib:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup git config
        run: |
          git config user.name = "GitHub Action Bot"
          git config user.email = "<>"

      - name: Bump jslib and commit
        id: bump
        run: |
          CHECKED_OUT_BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})

          if [ "$CHECKED_OUT_BRANCH_NAME" = "master" ]; then
            TARGET_BRANCH_NAME="auto-bump-jslib"

            git fetch origin

            TARGET_BRANCH_EXISTS=$(echo `git ls-remote --heads origin $TARGET_BRANCH_NAME | wc -l`)
            if [ "$TARGET_BRANCH_EXISTS" ]; then
              git checkout $TARGET_BRANCH_NAME
              echo "[*] Checked out existing branch $TARGET_BRANCH_NAME"
            else
              git checkout -b $TARGET_BRANCH_NAME
              echo "[*] Checked out new branch $TARGET_BRANCH_NAME"
            fi
          else
            TARGET_BRANCH_NAME="$CHECKED_OUT_BRANCH_NAME"
            echo "[*] Checked out existing feature branch $TARGET_BRANCH_NAME"
          fi

          npm run sub:init
          OLD_JSLIB_HASH=`git submodule status | awk '{print $1}'`

          npm run sub:update

          if [ `git diff --quiet jslib` ]; then
            echo "Unable to bump jslib: branch $CHECKED_OUT_BRANCH_NAME is already using the latest jslib commit."
            if [ "$TARGET_BRANCH_EXISTS" ]; then
              echo "Try merging the $TARGET_BRANCH_NAME branch first."
            exit 1
          fi

          git add jslib
          git commit -m "bump jslib"

          NEW_JSLIB_HASH=`git submodule status | awk '{print $1}'`
          echo "[*] Bumped jslib to $NEW_JSLIB_HASH"

          if [ "$CHECKED_OUT_BRANCH_NAME" = "master" ]; then
            git push -u origin $TARGET_BRANCH_NAME
          else
            git push origin $TARGET_BRANCH_NAME
          fi
          echo "[*] Pushed to $TARGET_BRANCH_NAME"

          cd jslib
          GIT_LOG=`git log $OLD_JSLIB_HASH..$NEW_JSLIB_HASH --oneline`
          
          echo "::set-output name=git-log::${GIT_LOG}"

      - name: Submit PR against master branch
        if: github.ref == 'refs/heads/master'
        run: |
          gh pr create --title "Auto bump jslib" \
            --body "@${{github.actor}} would like to bump jslib in this repo. This will pull in the following new commits:
              
            $GIT_LOG" \
            --reviewer eliykat
          
          echo "[*] Submitted PR against master branch"
        env:
          GIT_LOG: ${{ steps.bump.outputs.git-log }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
